=== Sutikshan/schemas/schema/omh/application-1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "description": "This schema represents an application that records some data about the individual.",
    "type": "object",

    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the source application."
        },
        "id": {
            "type": "string",
            "description": "The id of the source application."
        },
        "provider": {
            "type": "string",
            "description": "The provider of the source application."
        },
        "url": {
            "type": "string",
            "description": "The URL of the source application.",
            "format": "uri"
        },
        "version": {
            "type": "string",
            "description": "The version of the source application."
        },
        "platforms": {
            "type": "array",
            "items": [
                {
                    "os": {
                        "type": "string"
                    },
                    "version": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string",
                        "description": "The URL of the source application.",
                        "format": "uri"
                    }
                }
            ]
        }
    },
    "required": [
        "name"
    ]
}

=== Sutikshan/schemas/test-data/omh/application/1.0/shouldPass/valid-app.json
{
    "name": "MapMyRun",
    "id": "291890420",
    "provider": "UnderArmour",
    "version": "17.2.2",
    "url": "http://itunes.apple.com/us/app/imapmyrun/id291890420/?mt=8",
    "platforms": [
        {
            "os": {
                "type": "iOS"
            },
            "version": {
                "type": "9.3.5"
            }
        }
    ]
}
