=== Sutikshan/schemas/schema/omh/header-2.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "description": "This schema represents the header of a data transaction.",
    "type": "object",

    "definitions": {
        "date_time": {
            "$ref": "date-time-1.x.json"
        },
        "schema_id": {
            "$ref": "schema-id-1.x.json"
        },
        "device": {
            "$ref": "device-0.x.json"
        },
        "application":{
            "$ref": "application-0.x.json"
        }
    },

    "properties": {
        "id": {
            "description": "The identifier of this data point. We strongly recommend this to be a globally unique value.",
            "type": "string"
        },
        "creation_date_time": {
            "description": "The date time this data point was created.",
            "$ref": "#/definitions/date_time"
        },
        "schema_id": {
            "description": "The schema identifier of the body of the data point.",
            "$ref": "#/definitions/schema_id"
        },
        "acquisition_provenance": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "source": {
                        "oneOf": [
                            {
                                "device": {
                                    "description": "Device source of the data.",
                                    "$ref": "#/definitions/device"
                                },
                                "application": {
                                    "description": "Application source of the data.",
                                    "$ref": "#/definitions/application"
                                }
                            }
                        ]
                    },
                    "source_creation_date_time": {
                        "description": "The date time (timestamp) of data creation at the source.",
                        "$ref": "#/definitions/date_time"
                    },
                    "modality": {
                        "description": "The modality whereby the measure is obtained.",
                        "type": "string",
                        "enum": [
                            "sensed",
                            "self-reported"
                        ]
                    },
                    "placement": {
                        "description": "Placement of the device or measuring application.",
                        "type": "string",
                        "enum": [
                            "left ankle",
                            "right ankle",
                            "left hip",
                            "right hip",
                            "left thigh",
                            "right thigh",
                            "left thorax",
                            "middle left thorax",
                            "left upper arm",
                            "right upper arm",
                            "left wrist",
                            "right wrist"
                        ]
                    }
                },
                "required": [
                    "source",
                    "source_creation_date_time"
                ]
            }
        },
        "handedness": {
            "description": "The person's handedness, which indicates the dominant side.",
            "type": "string",
            "enum": [
                "ambidextrous",
                "left handed",
                "right handed",
                "unknown handedness"
            ]
        },
        "user_id": {
            "description": "The user this data point belongs to.",
            "type": "string"
        }
    },
    "required": [
        "id",
        "schema_id",
        "user_id"
    ]
}

=== Sutikshan/schemas/test-data/omh/header/2.0/shouldPass/with-device-and-app.json
{
    "id": "123e4567-e89b-12d3-a456-426655440000",
    "creation_date_time": "2013-02-05T07:25:00Z",
    "schema_id": {
        "namespace": "omh",
        "name": "physical-activity",
        "version": "1.1"
    },
    "acquisition_provenance": [
        {
            "source": {
                "device": {
                    "name": "Charge HR",
                    "manufacturer": "Fitbit",
                    "model": "Charge HR",
                    "id": "27072629"
                }
            },
            "placement": "left wrist",
            "source_creation_date_time": "2013-02-05T07:25:00Z",
            "modality": "sensed"
        },
        {
            "source": {
                "application": {
                    "name": "Map My Run",
                    "id": "291890420",
                    "provider": "UnderArmour",
                    "version": "17.2.2",
                    "url": "http://itunes.apple.com/us/app/imapmyrun/id291890420/?mt=8",
                    "platforms": [
                        {
                            "os": {
                                "type": "iOS"
                            },
                            "version": {
                                "type": "9.3.5"
                            }
                        }
                    ]
                }
            },
            "source_creation_date_time": "2013-02-05T07:25:00Z",
            "modality": "sensed"
        },
        {
            "source": {
                "application": {
                    "name": "Map My Fitness",
                    "id": "291890420",
                    "provider": "UnderArmour",
                    "version": "17.7.1",
                    "url": "https://itunes.apple.com/us/app/map-my-fitness-gps-workout-trainer-tracker/id298903147?mt=8",
                    "platforms": [
                        {
                            "os": {
                                "type": "iOS"
                            },
                            "version": {
                                "type": "9.3.5"
                            }
                        }
                    ]
                }
            },
            "source_creation_date_time": "2013-02-05T07:25:00Z",
            "modality": "sensed"
        }
    ],
    "handedness": "left handed",
    "user_id": "user1432"
}
